import { PCloudAccount, PCloudFile, Contact, ContactList, Template, Campaign, PCloudShareExecution, ErrorLog } from '../types';

export const mockUser = {
  id: 'usr-1',
  email: 'admin@autowork.com',
  firstName: 'Alex',
  lastName: 'Morgan',
  organizationId: 'org-101',
  role: 'ADMIN' as const,
};

export const mockOrganization = {
  id: 'org-101',
  name: 'Acme Growth Labs',
  slug: 'acme-growth',
};

export const mockAccounts: PCloudAccount[] = [
  {
    id: 'acc-1',
    name: 'Primary pCloud Storage Vault',
    accountEmail: 'primary@autowork.com',
    provider: 'pcloud',
    status: 'ACTIVE',
    dailyLimit: 1000,
    sentToday: 142,
    createdAt: '2026-08-01T10:00:00Z',
    lastUsedAt: '2026-08-13T10:00:00Z',
  },
  {
    id: 'acc-2',
    name: 'Mock Test Vault A',
    accountEmail: 'mock.vault@autowork.com',
    provider: 'mock_pcloud',
    status: 'ACTIVE',
    dailyLimit: 500,
    sentToday: 89,
    createdAt: '2026-08-05T14:30:00Z',
  },
  {
    id: 'acc-3',
    name: 'Secondary Archival pCloud',
    accountEmail: 'archive@autowork.com',
    provider: 'pcloud',
    status: 'PAUSED',
    dailyLimit: 250,
    sentToday: 0,
    createdAt: '2026-08-10T09:15:00Z',
  },
];

export const mockFiles: PCloudFile[] = [
  {
    id: 'file-1',
    pcloudAccountId: 'acc-1',
    name: 'Executive_Product_Overview.pdf',
    fileId: 'mock-file-101',
    folderId: '0',
    fileSize: 245000,
    mimeType: 'application/pdf',
    createdAt: '2026-08-10T12:00:00Z',
  },
  {
    id: 'file-2',
    pcloudAccountId: 'acc-1',
    name: 'Q3_Security_Audit_Report.pdf',
    fileId: 'mock-file-102',
    folderId: '0',
    fileSize: 512000,
    mimeType: 'application/pdf',
    createdAt: '2026-08-11T14:00:00Z',
  },
];

export const mockContacts: Contact[] = [
  {
    id: 'cnt-1',
    email: 'sarah.connor@cyberdyne.io',
    firstName: 'Sarah',
    lastName: 'Connor',
    fullName: 'Sarah Connor',
    phone: '+1 555-0192',
    company: 'Cyberdyne Systems',
    target: 'Enterprise IT Division',
    status: 'ACTIVE',
    createdAt: '2026-08-02T11:20:00Z',
  },
  {
    id: 'cnt-2',
    email: 'bruce.wayne@wayneenterprises.com',
    firstName: 'Bruce',
    lastName: 'Wayne',
    fullName: 'Bruce Wayne',
    phone: '+1 555-0144',
    company: 'Wayne Enterprises',
    target: 'Strategic Tech',
    status: 'ACTIVE',
    createdAt: '2026-08-03T12:00:00Z',
  },
  {
    id: 'cnt-3',
    email: 'diana.prince@themyscira.org',
    firstName: 'Diana',
    lastName: 'Prince',
    fullName: 'Diana Prince',
    phone: '+1 555-0188',
    company: 'Themyscira Global',
    target: 'Cloud Defense',
    status: 'ACTIVE',
    createdAt: '2026-08-04T15:10:00Z',
  },
  {
    id: 'cnt-4',
    email: 'clark.kent@dailyplanet.com',
    firstName: 'Clark',
    lastName: 'Kent',
    fullName: 'Clark Kent',
    phone: '+1 555-0177',
    company: 'Daily Planet News',
    target: 'Media Operations',
    status: 'ACTIVE',
    createdAt: '2026-08-06T08:45:00Z',
  },
  {
    id: 'cnt-5',
    email: 'tony.stark@starkindustries.com',
    firstName: 'Tony',
    lastName: 'Stark',
    fullName: 'Tony Stark',
    phone: '+1 555-0199',
    company: 'Stark Industries',
    target: 'Advanced Energy',
    status: 'ACTIVE',
    createdAt: '2026-08-08T16:30:00Z',
  },
];

export const mockContactLists: ContactList[] = [
  {
    id: 'lst-1',
    name: 'Enterprise VIP Prospects',
    description: 'Tier-1 executive contacts for Q3 pCloud distribution',
    memberCount: 5,
    createdAt: '2026-08-02T11:30:00Z',
  },
  {
    id: 'lst-2',
    name: 'SaaS Founders & CTOs',
    description: 'Targeted tech leads and decision makers',
    memberCount: 42,
    createdAt: '2026-08-05T09:00:00Z',
  },
];

export const mockTemplates: Template[] = [
  {
    id: 'tpl-1',
    name: 'Executive Document Distribution',
    description: 'Outreach template with dynamic recipient tokens and verification code',
    content: 'Hello #NAME#,\n\nPlease find the confidential document shared from our secure pCloud repository for #COMPANY#.\n\nYour security verification code: #RANDOM#\n\nBest regards,\nAlex Morgan\nAutowork Orchestrator',
    variables: ['#NAME#', '#COMPANY#', '#RANDOM#'],
    createdAt: '2026-08-03T10:15:00Z',
    updatedAt: '2026-08-11T14:20:00Z',
  },
  {
    id: 'tpl-2',
    name: 'Product Follow-Up Share',
    description: 'Follow-up document distribution with division token',
    content: 'Hi #FIRSTNAME#,\n\nFollowing up on our discussion regarding #TARGET#. Here is the full specification package.\n\nVerification Code: #RANDOM#\n\nCheers,\nAlex',
    variables: ['#FIRSTNAME#', '#TARGET#', '#RANDOM#'],
    createdAt: '2026-08-06T11:00:00Z',
    updatedAt: '2026-08-06T11:00:00Z',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'cmp-1',
    name: 'Q3 Enterprise pCloud Share Campaign',
    status: 'PROCESSING',
    pcloudAccountId: 'acc-1',
    pcloudAccount: mockAccounts[0],
    pcloudFileId: 'file-1',
    pcloudFile: mockFiles[0],
    templateId: 'tpl-1',
    template: mockTemplates[0],
    totalCount: 50,
    sharedCount: 38,
    failedCount: 1,
    retryingCount: 0,
    createdAt: '2026-08-12T09:00:00Z',
  },
  {
    id: 'cmp-2',
    name: 'SaaS Founders Nurture Distribution',
    status: 'COMPLETED',
    pcloudAccountId: 'acc-1',
    pcloudAccount: mockAccounts[0],
    pcloudFileId: 'file-2',
    pcloudFile: mockFiles[1],
    templateId: 'tpl-2',
    template: mockTemplates[1],
    totalCount: 42,
    sharedCount: 42,
    failedCount: 0,
    retryingCount: 0,
    createdAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'cmp-3',
    name: 'Draft Strategic Partner Share',
    status: 'DRAFT',
    pcloudAccountId: 'acc-1',
    pcloudAccount: mockAccounts[0],
    pcloudFileId: 'file-1',
    pcloudFile: mockFiles[0],
    templateId: 'tpl-1',
    template: mockTemplates[0],
    totalCount: 0,
    sharedCount: 0,
    failedCount: 0,
    retryingCount: 0,
    createdAt: '2026-08-12T11:30:00Z',
  },
];

export const mockExecutionLogs: PCloudShareExecution[] = [
  {
    id: 'exe-101',
    campaignId: 'cmp-1',
    campaign: { id: 'cmp-1', name: 'Q3 Enterprise pCloud Share Campaign' },
    pcloudAccountId: 'acc-1',
    pcloudAccount: mockAccounts[0],
    pcloudFileId: 'file-1',
    pcloudFile: mockFiles[0],
    recipientEmail: 'sarah.connor@cyberdyne.io',
    descriptionSnapshot: 'Hello Sarah Connor,\n\nPlease find the confidential document shared from our secure pCloud repository for Cyberdyne Systems.\n\nYour security verification code: A72K9P\n\nBest regards,\nAlex Morgan',
    operationType: 'sharefolder',
    status: 'SUCCESS',
    pcloudReferenceId: 'mock-share-883921',
    startedAt: '2026-08-12T09:05:12Z',
    completedAt: '2026-08-12T09:05:13Z',
  },
  {
    id: 'exe-102',
    campaignId: 'cmp-1',
    campaign: { id: 'cmp-1', name: 'Q3 Enterprise pCloud Share Campaign' },
    pcloudAccountId: 'acc-1',
    pcloudAccount: mockAccounts[0],
    pcloudFileId: 'file-1',
    pcloudFile: mockFiles[0],
    recipientEmail: 'bruce.wayne@wayneenterprises.com',
    descriptionSnapshot: 'Hello Bruce Wayne,\n\nPlease find the confidential document shared from our secure pCloud repository for Wayne Enterprises.\n\nYour security verification code: B99KP1\n\nBest regards,\nAlex Morgan',
    operationType: 'sharefolder',
    status: 'SUCCESS',
    pcloudReferenceId: 'mock-share-883922',
    startedAt: '2026-08-12T09:05:15Z',
    completedAt: '2026-08-12T09:05:16Z',
  },
];

export const mockErrorLogs: ErrorLog[] = [
  {
    id: 'err-1',
    code: 'PCLOUD_RATE_LIMITED',
    message: 'pCloud API rate limit reached on account Primary Vault (4000). Exponential backoff scheduled.',
    createdAt: '2026-08-12T09:05:18Z',
  },
];
