# Autowork.com Backend Dockerfile
FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache openssl
COPY backend/package*.json ./
COPY prisma ./prisma
RUN npm install

COPY backend/ ./
RUN npx prisma generate --schema=./prisma/schema.prisma
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
RUN apk add --no-cache openssl
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 4000
CMD ["node", "dist/main"]
