# Autowork.com pCloud worker Dockerfile
FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache openssl
COPY backend/package*.json ./
RUN npm install

COPY backend/ ./backend/
COPY prisma ./prisma
COPY workers ./workers
RUN npx prisma generate --schema=./prisma/schema.prisma
RUN npm --prefix ./backend run build

FROM node:20-alpine AS runner
WORKDIR /app/backend

ENV NODE_ENV=production
ENV NODE_PATH=/app/node_modules
RUN apk add --no-cache openssl
COPY --from=builder /app/backend/package*.json ./
COPY --from=builder /app/backend/dist ./dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/prisma ../prisma
COPY --from=builder /app/backend/src ./src
COPY --from=builder /app/workers ../workers

CMD ["npx", "ts-node", "--transpile-only", "../workers/pcloud-share.worker.ts"]
