export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  ACCOUNTS: '/accounts',
  CONTACTS: '/contacts',
  IMPORTS: '/imports',
  TEMPLATES: '/templates',
  CAMPAIGNS: '/campaigns',
  CAMPAIGNS_NEW: '/campaigns/new',
  AUTOMATIONS: '/automations',
  ATTACHMENTS: '/attachments',
  LOGS: '/logs',
  SETTINGS: '/settings',
  ADMIN: '/admin',
} as const;
